name: Check Release
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]
  release:
    types: [published]
  schedule:
    - cron: "0 0 * * *"

jobs:
  check_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - name: Install Dependencies
        shell: bash
        run: |
          pip install -e .
      - name: Check Release
        uses: ./.github/actions/check-release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Distributions
        uses: actions/upload-artifact@v3
        with:
          name: jupyterlab_urdf-releaser-dist-${{ github.run_number }}
          path: .jupyter_releaser_checkout/dist
